# platform vars
image_ansible_version: '2.9.*'
molecule_version: '3.1.*'
docker_version: '20-dind'

# ci
prepare_image_task: ansible-ci

# get latest versions
version_regex: '(?<=[\/v|\/])([0-9]+)\.([0-9]+)\.([0-9]+)'

# jx
# jx3_version_install: true
# jx3_version_url: https://github.com/jenkins-x/jx-cli/releases/latest
# jx3_version_regex: '(?<=[\/v|\/])([0-9]+)\.([0-9]+)\.([0-9]+)'
# jx2_version_install: true
# jx2_version_url: https://github.com/jenkins-x/jx/releases/latest
# jx2_version_regex: '(?<=[\/v|\/])([0-9]+)\.([0-9]+)\.([0-9]+)'

# oras
oras_version_install: true
oras_version_url: https://github.com/deislabs/oras/releases/latest
oras_version_regex: "{{ version_regex }}"

# pushrm
pushrm_version_install: true
pushrm_version_url: https://github.com/christian-korneck/docker-pushrm/releases/latest
pushrm_version_regex: "{{ version_regex }}"

# buildx
buildx_version_install: true
buildx_version_url: https://github.com/docker/buildx/releases/latest
buildx_version_regex: "{{ version_regex }}"

# terraform
terraform_version_install: true
terraform_version_url: https://github.com/hashicorp/terraform/releases/latest
terraform_version_regex: "{{ version_regex }}"
