# platform vars
centos_version: '8'
php_version: '7.2'
httpd_version: '2.4'
nginx_version: '1.14'
postgres_version: '13'
postgres_prev_version: '10'

# builder
# dockerfile_builder_push: true
container_builder_image_from: base-stream
dockerfile_builder_image_pkgs_mgm: microdnf --setopt=tsflags=nodocs -y
