# container
ctr_name: "{{ ansible_host }}"
## state name must comply with ansible variable name convention
state_name: "{{ ctr_name | replace('-', '_') | lower }}"

# containers template dir
template_dir: templated_contexts
template_path: "{{ template_dir }}/{{ ctr_name }}"

# containers generated build dir
generated_dir: generated_contexts
generated_path: "{{ generated_dir }}/{{ ctr_name }}"

# registry
registry_name: "quay.io"
registry_project: krestomatio
registry_path: "{{ registry_name + '/' if registry_name else '' }}{{registry_project}}"
cache_registry_name: gcr.io
build_registry_name: gcr.io

# build vars
dockerfile_builder: docker
# dockerfile_builder_push: true
dockerfile_builder_image_timezone: UTC
dockerfile_builder_image_authors: Job CÃ©spedes Ortiz <jobcespedes@gmail.com>
dockerfile_builder_image_based: CentOS 8 minimal
dockerfile_builder_image_from:
  "{{ registry_path }}/{{ image_from }}{{ ':' + container_builder_image_tag_from
  if container_builder_image_tag_from is defined
  and container_builder_image_tag_from else '' }}"
dockerfile_builder_image: "{{ registry_path }}/{{ ctr_name }}"
dockerfile_builder_path: "{{ generated_path }}"
dockerfile_builder_src: "{{ template_path }}"
dockerfile_builder_sync_checksum: true
