# origin
origin_name: gitlab.com
origin_project: krestomatio/m4s

# registry
registry_name: quay.io
registry_project: krestomatio

# platform vars
php_version: '7.2'
httpd_version: '2.4'
moodle_version: '3.5'

# builder
# dockerfile_builder_image_push: true
dockerfile_builder_image_pkgs_mgm: microdnf --setopt=tsflags=nodocs -y
dockerfile_builder_image_timezone: America/Costa_Rica
dockerfile_builder_image_created:
  "{{ item.image_created | default(ansible_date_time.iso8601) }}"
dockerfile_builder_image_authors: Job CÃ©spedes Ortiz <jobcespedes@gmail.com>
