ctr_repo_name: httpd

# version tags
version_image_major: "{{ httpd_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ httpd_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ httpd_version.split('.')[2] | default(false) }}"
