# ci
version_release_no_bump: true

# version tags
version_image_major: "{{ keydb_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ keydb_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ keydb_version.split('.')[2] | default(false) }}"
