node_version: "{{ node_versions.14 }}"
version_image_suffix: ci
image_from_ctr: "node{{ node_version }}"
image_tag_from_ctr: "{{ node_version }}"
dockerfile_builder_image_from_repo_name: node
dockerfile_builder_tags:
- "{{ node_version_name[node_version|int] }}-ci"

dockerfile_builder_image_ocp_tags: "node,node{{ node_version }},node-{{ node_version_name[node_version|int] }},node-ci,ci"

# containers generated build dir
template_path: "{{ template_dir }}/node-ci"
