# platform vars
operator_version: 1.21.0
kustomize_version: 4.1.3
kubectl_version: 1.23.6

container_builder_image_from: ansible-podman-ci
dockerfile_builder_image_ocp_tags: "ansible,ansible{{ image_ansible_version }},ansible-operator,ansible-operator{{ operator_version }}"
